#!/bin/bash -l
# THE SAMPLED SWEEP -- 22 cells x 3 seeds, per docs/AGENT_B_INBOX.md "LAUNCH THE SAMPLED
# SWEEP ON MYRIAD. This is the critical path." n_int=200 baseline, confirmed viable by two
# independent feasibility searches (930aa65 at k=8, sampled_feasibility_smallk.json at k=9)
# after n_int=20-60 showed no separation anywhere.
#
# RESUMABLE BY DESIGN. Each task runs through `scripts/resume_or_start.sh`, which checks
# for a finished result first (skip), then the highest `_resume_uNNNN.pt` (continue from
# there), then starts from scratch -- because no single Myriad walltime slot covers every
# cell here (k=30 alone is 12.3h/run measured elsewhere) and jobs WILL be killed by
# walltime. Re-submitting this same script is the intended recovery: every finished task
# skips, every unfinished one advances from its last checkpoint.
#
# Reads one line per array task from `sampled_jobs_array.txt`, generated by:
#   scripts/sweep.py --emit jobs --seeds 3 --evidence sampled --out_dir results/sweep/sampled
#       --episodes 4000 --extra "--turn_aware_credit --local_epochs 4"
# then piped through resume_or_start.sh substitution -- see the commit this file ships in
# for the exact sed. Never hand-retype a sweep command.
#
#$ -N sampled_sweep
#$ -cwd
#$ -t 1-66
#$ -l h_rt=12:00:00
#$ -l mem=16G
#$ -pe smp 1
#$ -o logs/
#$ -e logs/

set -uo pipefail
mkdir -p logs results/sweep/sampled
source ~/envs/sa_env/bin/activate
cd ~/ma_tb
export PYTHONPATH=.
export TMPDIR=~/.tmp
mkdir -p ~/.tmp
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1

CMD=$(sed -n "${SGE_TASK_ID}p" sampled_jobs_array.txt)
echo "=== task $SGE_TASK_ID : $(date) ==="
echo "cmd: $CMD"
eval "$CMD"
echo "=== done $(date) ==="
