"""Generate `thesis_results/CLAIMS.md`: the sentence-level facts Chapter 4 may assert.

WHY. The ledger is a working document and has been wrong twice: section 2.2 quoted a
share-of-ceiling as a raw rate, and section 1.3 reported an asymmetry that a larger
re-measurement retracted. Chapter 4 needs a source that is derived from the data files rather
than maintained by hand, and that carries the boundary of each claim next to the number.

Every figure below is computed at generation time from `thesis_results/`. The MUST NOT lines
are hand-maintained, because a retraction is a judgement and not a computation -- they are the
part to read before writing a sentence.
"""
from __future__ import annotations
import glob, json, pathlib
import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[1]
TR = ROOT / "thesis_results"
FLOOR, TAIL = 0.70, 10


def wr(d):
    t = [h.get("window_rate", 0.0) for h in (d.get("history") or [])[-TAIL:]]
    return sum(t) / len(t) if t else 0.0


def sweep(pattern):
    return [json.loads(p.read_text()) for p in sorted((TR / "sweep").glob(pattern))]


def ck(k, which):
    return json.loads((TR / "checkpoint" / f"k{k:02d}_{which}.json").read_text())


def fed(name):
    return [json.loads(p.read_text()) for p in sorted((TR / "federation").glob(name))]


out = ["# Claims — what Chapter 4 may assert, with the number and its boundary", "",
       "Generated by `scripts/build_claims.py` from `thesis_results/`. **Do not edit the",
       "numbers by hand.** The MUST NOT lines are hand-maintained and are the important part.",
       "", "Regenerate after `scripts/collect_thesis_results.py`.", ""]

# --- RQ1: crossover -----------------------------------------------------------------------
out += ["## C1 — The advantage changes sign between $k_v=8$ and $k_v=12$", "",
        "| $k_v$ | recovery L | recovery M | SHD L (selected) | SHD L (final) | SHD M |",
        "|---|---|---|---|---|---|"]
for k in (4, 8, 12, 20, 30):
    s = sweep(f"k{k:02d}s50n04b150_s*.json")
    rl = np.mean([r["arms"]["learned"]["success"] for r in s])
    rm = np.mean([r["arms"]["greedy_uncertainty"]["success"] for r in s])
    b = np.mean([r["means"]["learned"]["hard"] for r in ck(k, "best")])
    f = np.mean([r["means"]["learned"]["hard"] for r in ck(k, "final")])
    m = np.mean([r["means"]["greedy"]["hard"] for r in ck(k, "best")])
    out.append(f"| {k} | {rl:.3f} | {rm:.3f} | {b:.5f} | {f:.5f} | {m:.5f} |")
out += ["",
        "**Boundary.** Recovery rate is the final policy; SHD is reported at both checkpoints.",
        "At $k_v=30$ the paired per-seed differences are +0.00054 +/- 0.00063, -0.00040 +/-",
        "0.00008 and -0.00026 +/- 0.00007: two seeds significant, one indistinguishable.",
        "**MUST NOT** quote a ratio of means at $k_v=30$; it hides that one seed carries it.", ""]

# --- RQ1: agent count ---------------------------------------------------------------------
out += ["## C2 — The advantage reverses as agents are added", "",
        "| $K$ | SHD L | SHD M | ratio | ratio excl. seed 2 | seeds |", "|---|---|---|---|---|---|"]
for n in (2, 3, 4, 5, 8, 10):
    rows = [r for r in sweep(f"k12s50n{n:02d}b150_s*.json") if wr(r) >= FLOOR]
    L = [r["arms"]["learned"]["global_hard_shd"] for r in rows]
    G = [r["arms"]["greedy_uncertainty"]["global_hard_shd"] for r in rows]
    S = [r.get("seed") for r in rows]
    L2 = [v for v, s in zip(L, S) if s != 2]
    G2 = [v for v, s in zip(G, S) if s != 2]
    r2 = (np.mean(L2) / np.mean(G2)) if L2 else float("nan")
    out.append(f"| {n} | {np.mean(L):.5f} | {np.mean(G):.5f} | {np.mean(L)/np.mean(G):.2f} | "
               f"{r2:.2f} | {len(rows)} |")
out += ["",
        "**Boundary.** At $K=5$ the reversal is one seed: 1.65 with all seeds, 0.25 without.",
        "State the reversal as beginning at eight agents. Both figures must appear.",
        "**UNDER TEST 2 Sep 09:0x.** `k12s50n08b150_s2` and `k12s50n10b150_s2` passed the",
        "competence floor at 0.838 and 0.804 but may be unconverged; both are retraining at",
        "12,000 episodes. Until they land, prefer the seed-2-excluded ratios.",
        "**MUST NOT** claim the myopic rule improves across this axis. Per-pair SHD divides by",
        "`global_pairs`, which runs 117 -> 525; in raw counts the myopic arm is close to flat.", ""]

# --- RQ1: pair class ----------------------------------------------------------------------
pc = json.loads((ROOT / "results/shd_by_class_200.json").read_text())
out += ["## C3 — The learned advantage is entirely on scored pairs", "",
        "| arm | private-incident | shared-shared |", "|---|---|---|"]
for arm in ("learned", "greedy", "random"):
    out.append(f"| {arm} | {np.mean([e['arms'][arm]['private_incident'] for e in pc]):.5f} | "
               f"{np.mean([e['arms'][arm]['shared_shared'] for e in pc]):.5f} |")
out += ["", f"6 runs, 200 episodes, `_best.pt`. "
        f"{sum(e['arms']['learned']['n_private'] for e in pc):,} private-incident and "
        f"{sum(e['arms']['learned']['n_shared'] for e in pc):,} shared-shared observations.",
        "**MUST NOT** write the reward-alignment asymmetry (ledger 1.3). RETRACTED:",
        "shared-shared error is 0.00000 for both learned and myopic, maximum across all six runs.", ""]

# --- RQ3 ------------------------------------------------------------------------------------
A = fed("shd_A.json") + fed("shd_A_s345.json")
E = fed("shd_E.json") + fed("shd_E_s345.json")
LA = [x["means"]["learned"]["hard"] for e in A for x in e]
LE = [x["means"]["learned"]["hard"] for e in E for x in e]
G = [x["means"]["greedy"]["hard"] for e in A for x in e]
d = np.array(LA) - np.array(LE)
se = d.std(ddof=1) / np.sqrt(len(d))
out += ["## C4 — Federating information, reward and optimisation costs nothing measurable", "",
        f"* federated SHD mean {np.mean(LA):.5f}, median {np.median(LA):.5f}",
        f"* centralised SHD mean {np.mean(LE):.5f}, median {np.median(LE):.5f}",
        f"* myopic on the same episodes {np.mean(G):.5f}",
        f"* **paired federated - centralised over {len(d)} seeds: {d.mean():+.5f} +/- {se:.5f}"
        f" ({'inside' if abs(d.mean()) <= 2*se else 'outside'} 2 SE)**", "",
        "**Boundary.** Action rights stay partitioned in both arms. This is the cost of",
        "partitioning information, reward and optimisation, not of decentralisation entire.",
        "**MUST NOT** state a direction: mean and median disagree on which arm leads.", ""]

# --- Undertraining ---------------------------------------------------------------------------
out += ["## C5 — The competence-floor exclusions are undertrained, not broken", "",
        "| cell (seed 2) | 4,000 ep wr / learned | 12,000 ep wr / learned | myopic |",
        "|---|---|---|---|"]
for p in sorted((TR / "federation").glob("*_long_s2.json")):
    cell = p.name.replace("_long_s2.json", "")
    d12 = json.loads(p.read_text())
    d4 = json.loads((TR / "sweep" / f"{cell}_s2.json").read_text())
    out.append(f"| {cell} | {wr(d4):.3f} / {d4['arms']['learned']['success']:.3f} | "
               f"**{wr(d12):.3f} / {d12['arms']['learned']['success']:.3f}** | "
               f"{d12['arms']['greedy_uncertainty']['success']:.3f} |")
out += ["",
        "All seven pass the floor and all seven beat the myopic rule when converged. Halving the",
        "learning rate instead makes them worse (0.519 -> 0.206, 0.345 -> 0.177).",
        "**MUST NOT** substitute these into any sweep table. The sweep holds the training budget",
        "fixed at 4,000 episodes across all twenty cells; mixing budgets between cells would",
        "confound the axis being varied. Report them beside the sweep as a limitation of it.", ""]

path = TR / "CLAIMS.md"
path.write_text("\n".join(out))
print(f"wrote {path.relative_to(ROOT)}: {len(out)} lines")
