"""Generate `thesis_results/CLAIMS.md`: the sentence-level facts Chapter 4 may assert.

WHY. The ledger is a working document and has been wrong twice: section 2.2 quoted a
share-of-ceiling as a raw rate, and section 1.3 reported an asymmetry that a larger
re-measurement retracted. Chapter 4 needs a source that is derived from the data files rather
than maintained by hand, and that carries the boundary of each claim next to the number.

Every figure below is computed at generation time from `thesis_results/`. The MUST NOT lines
are hand-maintained, because a retraction is a judgement and not a computation -- they are the
part to read before writing a sentence.
"""
from __future__ import annotations
import glob, json, pathlib
import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[1]
TR = ROOT / "thesis_results"
FLOOR, TAIL = 0.70, 10


def wr(d):
    t = [h.get("window_rate", 0.0) for h in (d.get("history") or [])[-TAIL:]]
    return sum(t) / len(t) if t else 0.0


def sweep(pattern):
    return [json.loads(p.read_text()) for p in sorted((TR / "sweep").glob(pattern))]


def ck(k, which):
    return json.loads((TR / "checkpoint" / f"k{k:02d}_{which}.json").read_text())


def fed(name):
    return [json.loads(p.read_text()) for p in sorted((TR / "federation").glob(name))]


out = ["# Claims — what Chapter 4 may assert, with the number and its boundary", "",
       "Generated by `scripts/build_claims.py` from `thesis_results/`. **Do not edit the",
       "numbers by hand.** The MUST NOT lines are hand-maintained and are the important part.",
       "", "Regenerate after `scripts/collect_thesis_results.py`.", ""]

# --- RQ1: crossover -----------------------------------------------------------------------
out += ["## C1 — The advantage changes sign between $k_v=8$ and $k_v=12$", "",
        "| $k_v$ | recovery L | recovery M | SHD L (selected) | SHD L (final) | SHD M |",
        "|---|---|---|---|---|---|"]
for k in (4, 8, 12, 20, 30):
    s = sweep(f"k{k:02d}s50n04b150_s*.json")
    rl = np.mean([r["arms"]["learned"]["success"] for r in s])
    rm = np.mean([r["arms"]["greedy_uncertainty"]["success"] for r in s])
    b = np.mean([r["means"]["learned"]["hard"] for r in ck(k, "best")])
    f = np.mean([r["means"]["learned"]["hard"] for r in ck(k, "final")])
    m = np.mean([r["means"]["greedy"]["hard"] for r in ck(k, "best")])
    out.append(f"| {k} | {rl:.3f} | {rm:.3f} | {b:.5f} | {f:.5f} | {m:.5f} |")
out += ["",
        "**Boundary.** Recovery rate is the final policy; SHD is reported at both checkpoints.",
        "SHD is measured under a seeded evaluation (2 Sep 22:xx). The myopic column reproduces",
        "the pre-fix measurement to five decimals at every $k_v$; the learned column moved by",
        "0.00 to 0.99 paired SE. `FINDINGS_DETERMINISM_2026_09_02.md`",
        "At $k_v=30$ the paired per-seed differences are -0.00009 +/- 0.00034, -0.00040 +/-",
        "0.00008 and -0.00005 +/- 0.00021: **one seed of three separates**, two are",
        "indistinguishable. The earlier reading of this line said two of three; that was",
        "measured before the evaluation RNG was seeded and is withdrawn.",
        "**MUST NOT** quote a ratio of means at $k_v=30$; one seed carries the whole of it.",
        "**MUST NOT** read this axis as monotone in $k_v$, and MUST NOT say the sweep holds the",
        "training budget fixed. It does not. Verified from `config.train_episodes` over all 60",
        "runs: 18 cells at 4,000 episodes and 2 at 12,000, and the two at 12,000 are",
        "`k20s50n04b150` and `k30s50n04b150` -- the two that carry the headline. Window size and",
        "training budget are perfectly collinear across the last two points.",
        "(FINDINGS_WINDOW_BUDGET_CONFOUND_2026_09_02.md, agent C.)",
        "**WHAT SURVIVES, and it is more than that note allows.** $k_v=4$, $8$ and $12$ are all",
        "at 4,000 episodes, so the recovery gap over those three points -- -0.075, -0.025, +0.058",
        "-- is a clean within-budget comparison, and it contains the sign change. The monotone",
        "trend and the crossover may both be stated over $k_v \\le 12$. What may NOT be done is",
        "extend the trend to $k_v=20$ and $30$, where the budget triples with the window.",
        "The uniform-budget version of this axis is `tab:12k_k` in thesis/Tables12k.tex, which",
        "reports all five windows at 12,000 episodes.",
        "**MUST NOT** describe $k_v=8$ as favouring either arm. Per seed the paired differences",
        "are -0.00016 (ns), -0.00059 (SIG, learned ahead) and +0.00096 (ns): the seeds disagree",
        "and the mean is carried by seed 2. The crossover is between 8 and 12, and 8 is the",
        "cell where it is ambiguous rather than the last cell the myopic rule wins.", ""]

# --- RQ1: agent count, at the converged budget --------------------------------------------
# REWRITTEN 2 Sep 23:xx. The previous version of this claim read each run's own
# `global_hard_shd` at 4,000 episodes and carried an UNRESOLVED banner all day. Both problems
# are gone: the 12,000-episode sweep is complete and measured properly with
# scripts/global_shd_paired.py at both checkpoint conventions.
PRE12 = {"k12s50n05b150": "results/longcheck/shd_n05_12k.json",
         "k12s75n04b150": "results/longcheck/shd_s75_12k.json",
         "k12s50n08b150": "results/longcheck/shd_n08_12k.json",
         "k12s50n10b150": "results/longcheck/shd_n10_12k.json"}


def m12(cell, conv="best"):
    """A 12,000-episode cell, measured. Returns None rather than improvising when absent."""
    if conv == "best":
        q = ROOT / PRE12[cell] if cell in PRE12 else ROOT / f"results/sweep12k/shd/{cell}.json"
    else:
        q = ROOT / f"results/sweep12k/shd_{conv}/{cell}.json"
    if not q.exists():
        return None
    d = json.loads(q.read_text())
    return dict(L=np.mean([e["means"]["learned"]["hard"] for e in d]),
                M=np.mean([e["means"]["greedy"]["hard"] for e in d]),
                ahead=sum(1 for e in d if e["paired"]["learned-greedy"]["delta"] < 0),
                sig=sum(1 for e in d if e["paired"]["learned-greedy"]["delta"] < 0
                        and e["paired"]["learned-greedy"]["significant"]),
                n=len(d))


def rec(cell, budget):
    d = "results/sweep12k" if budget == 12000 else "results/sweep/oracle"
    fs = sorted(glob.glob(str(ROOT / d / f"{cell}_s?.json")))
    if not fs:
        return None
    j = [json.loads(open(f).read()) for f in fs]
    return (np.mean([x["arms"]["learned"]["success"] for x in j]),
            np.mean([x["arms"]["greedy_uncertainty"]["success"] for x in j]))


out += ["## C2 — At a converged budget the agent-count reversal does not exist", "",
        "| $K$ | SHD L (sel) | SHD L (fin) | SHD M | ratio (sel) | seeds ahead | beyond 2 SE |",
        "|---|---|---|---|---|---|---|"]
for n in (2, 3, 4, 5, 8, 10):
    cell = f"k12s50n{n:02d}b150"
    b, f = m12(cell), m12(cell, "final")
    if not b or not f:
        out.append(f"| {n} | *not measured* | | | | | |")
        continue
    out.append(f"| {n} | {b['L']:.5f} | {f['L']:.5f} | {b['M']:.5f} | "
               f"{b['L']/b['M'] if b['M'] else float('nan'):.2f} | {b['ahead']}/{b['n']} | "
               f"{b['sig']}/{b['n']} |")
out += ["",
        "12,000 episodes, three seeds per cell, 200 paired episodes per seed, selected and",
        "final checkpoints, seeded evaluation.",
        "",
        "**The reversal reported at 4,000 episodes is gone.** Ratios there ran 0.12, 0.33, 0.10,",
        "1.65, 4.24, 6.75 and were read as the advantage falling away with coordination load.",
        "At 12,000 the learned arm leads on the mean at every $K$ except 2, and $K=2$ is a",
        "single seed (below).",
        "",
        "**MUST NOT** state an agent-count reversal. It was a training-budget artefact, the",
        "third of three structural claims to resolve that way.",
        "**MUST NOT** quote the $K=2$ ratio of 15.97 without the seed behind it.",
        "`k12s50n02b150` seed 2 measures **0.07372** at the selected checkpoint and **0.00000**",
        "at the final update on the same episodes: the MI gate retained a policy 570x worse than",
        "the one at the last update. That one seed is the whole of the $K=2$ column. Report it",
        "as a checkpoint-selection failure, which is what it is, not as a two-agent result.",
        "**MUST NOT** claim the myopic rule improves across this axis. Per-pair SHD divides by",
        "`global_pairs`, which runs 117 -> 525; in raw counts the myopic arm is close to flat.",
        "**MUST NOT** read the significance column as weak evidence of nothing: 1/3 significant",
        "with 3/3 ahead at $K=5$, $8$ and $10$ reflects errors near zero in both arms, where a",
        "paired difference has little room to clear 2 SE.", ""]

# --- RQ1: the training budget, which is the headline of the sweep --------------------------
cells12 = sorted({q.stem for q in (ROOT / "results/sweep12k/shd_final").glob("*.json")})
a4 = a12 = flip = tie = 0
for cell in cells12:
    r4, r12 = rec(cell, 4000), rec(cell, 12000)
    if not r4 or not r12:
        continue
    M = r4[1]
    a4 += r4[0] > M
    a12 += r12[0] > M
    tie += abs(r12[0] - M) < 1e-9
    flip += (r4[0] <= M) and (r12[0] > M)
out += ["## C7 — The training budget, not any swept parameter, decides who wins", "",
        f"* Joint recovery, learned ahead of myopic: **{a4} of {len(cells12)} cells at 4,000",
        f"  episodes, {a12} of {len(cells12)} at 12,000**.",
        f"* {flip} cells change winner. {tie} is an exact tie at 12,000.",
        "* The myopic arm does not train, so its number is identical at both budgets. The",
        "  comparison is one policy against two, not two experiments.",
        "",
        "**Boundary.** This is joint recovery, the criterion the runs record themselves. The",
        "structural distance tables are measured separately and are not interchangeable with it.",
        "**MUST NOT** describe this as 15 of 18 cells flipping. It is 14; the fifteenth",
        "(`k12s50n05b150`) is an exact tie at 0.957 against 0.957 and was miscounted on 2 Sep",
        "by a comparison that treated a tie as a change of winner.", ""]

# --- RQ1: pair class ----------------------------------------------------------------------
pc = json.loads((ROOT / "results/shd_by_class_200.json").read_text())
out += ["## C3 — The learned advantage is entirely on scored pairs", "",
        "| arm | private-incident | shared-shared |", "|---|---|---|"]
for arm in ("learned", "greedy", "random"):
    out.append(f"| {arm} | {np.mean([e['arms'][arm]['private_incident'] for e in pc]):.5f} | "
               f"{np.mean([e['arms'][arm]['shared_shared'] for e in pc]):.5f} |")
out += ["", f"6 runs, 200 episodes, `_best.pt`. "
        f"{sum(e['arms']['learned']['n_private'] for e in pc):,} private-incident and "
        f"{sum(e['arms']['learned']['n_shared'] for e in pc):,} shared-shared observations.",
        "**MUST NOT** write the reward-alignment asymmetry (ledger 1.3). RETRACTED.", ""]

# The retraction above was justified with 'shared-shared error is 0.00000 for both arms,
# maximum across all six runs'. True of those six (k=20 and k=30) and NOT true in general:
# on the agent-count axis the learned arm is nonzero on the least-converged seeds. Measured
# properly at 12,000 episodes the effect is real in direction and negligible in size, which
# is a better defence of the retraction than a blanket zero that does not hold everywhere.
pc12 = ROOT / "results/shd_by_class_naxis_12k.json"
pc04 = ROOT / "results/shd_by_class_naxis_det.json"
if pc12.exists() and pc04.exists():
    def tally(path):
        d = json.loads(path.read_text())
        t = {}
        for arm in ("learned", "greedy", "random"):
            t[arm] = (sum(e["arms"][arm]["private_incident"] * e["arms"][arm]["n_private"] for e in d),
                      sum(e["arms"][arm]["n_private"] for e in d),
                      sum(e["arms"][arm]["shared_shared"] * e["arms"][arm]["n_shared"] for e in d),
                      sum(e["arms"][arm]["n_shared"] for e in d))
        return t, len(d)
    t4, n4 = tally(pc04)
    t12, n12 = tally(pc12)
    out += ["### C3a — training acts on the rewarded class and not on the other", "",
            "| budget | arm | rewarded errors | unrewarded errors |", "|---|---|---|---|"]
    for lbl, t in (("4,000", t4), ("12,000", t12)):
        for arm in ("learned", "greedy"):
            out.append(f"| {lbl} | {arm} | {t[arm][0]:.0f} / {t[arm][1]:,} | "
                       f"{t[arm][2]:.0f} / {t[arm][3]:,} |")
    out += [f"| either | random | {t4['random'][0]:.0f} / {t4['random'][1]:,} | "
            f"{t4['random'][2]:.0f} / {t4['random'][3]:,} |", "",
            f"{n12} runs on the agent-count axis, three seeds per cell, 200 episodes each, "
            "selected checkpoint. The myopic and random arms do not train and are identical at "
            "both budgets, which is what makes this controlled.", "",
            f"**Tripling the budget cuts rewarded-class errors {t4['learned'][0]/t12['learned'][0]:.1f}x "
            f"({t4['learned'][0]:.0f} to {t12['learned'][0]:.0f}) and leaves the unrewarded class "
            f"at {t12['learned'][2]:.0f}.** At 4,000 episodes the learned arm is worse than the "
            "myopic rule on both classes; at 12,000 it is better on the class it is scored on "
            "and unchanged on the class it is not.",
            "",
            "**MUST quote the magnitude with the claim.** 11 errors in 27,000 observations is "
            "0.04%. The asymmetry is real in direction and immaterial in size, and a sentence "
            "that gives the direction without the size overstates it.",
            "**MUST NOT** say the unrewarded class is exactly unchanged. With 11 events the "
            "Poisson SE is about 3.3, so this is no DETECTABLE change; an effect under roughly "
            "3 errors would be invisible here.",
            "**MUST NOT** read anything into which cells carry the errors. The eleven sit in "
            "entirely different runs at the two budgets.",
            "**MUST NOT** restore the blanket 'zero for both arms' justification. It holds for "
            "the six $k_v=20$ and $30$ runs and nowhere else.", ""]

# --- RQ3 -------------------------------------------------------------------------------------
# 12,000 episodes. The six-seed result this claim carried until 3 Sep was measured on
# 4,000-episode policies, and its one significant seed was an unconverged centralised run whose
# error was 0.00263 against 0.00000-0.00066 elsewhere. At 12,000 that seed measures 0.00000.
LAD = {k: {r["seed"]: r for r in json.loads(
        (ROOT / f"results/rerows/ladder12k_{k}.json").read_text())}
       for k in ("A_best", "A_final", "E_best", "E_final")
       if (ROOT / f"results/rerows/ladder12k_{k}.json").exists()}
if len(LAD) == 4:
    seeds = sorted(LAD["A_best"])
    ds = []
    for sd in seeds:
        x = np.array(LAD["A_best"][sd]["rows"]["learned"]["hard"])
        y = np.array(LAD["E_best"][sd]["rows"]["learned"]["hard"])
        ds.append((x - y).mean())
    ds = np.array(ds)
    gv = lambda k: [LAD[k][sd]["means"]["learned"]["hard"] for sd in seeds]
    myo = [LAD["A_best"][sd]["means"]["greedy"]["hard"] for sd in seeds]
    sig = sum(1 for sd in seeds
              if abs((np.array(LAD["A_best"][sd]["rows"]["learned"]["hard"]) -
                      np.array(LAD["E_best"][sd]["rows"]["learned"]["hard"])).mean())
              > 2 * (np.array(LAD["A_best"][sd]["rows"]["learned"]["hard"]) -
                     np.array(LAD["E_best"][sd]["rows"]["learned"]["hard"])).std(ddof=1)
              / np.sqrt(200))
    out += ["## C4 — Federating information, reward and optimisation costs nothing measurable", "",
            f"* federated SHD mean {np.mean(gv('A_best')):.5f}, median {np.median(gv('A_best')):.5f}",
            f"* centralised SHD mean {np.mean(gv('E_best')):.5f}, median {np.median(gv('E_best')):.5f}",
            f"* myopic on the same episodes {np.mean(myo):.5f}",
            f"* **paired federated - centralised over {len(seeds)} seeds: "
            f"{ds.mean():+.5f} +/- {ds.std(ddof=1)/np.sqrt(len(ds)):.5f}**",
            f"* **{sig} of {len(seeds)} seeds separate beyond 2 SE**",
            f"* final-update convention: federated {np.mean(gv('A_final')):.5f}, "
            f"centralised {np.mean(gv('E_final')):.5f}",
            "",
            "12,000 episodes, four agents, $k_v=12$, 200 paired episodes per seed, seeded",
            "evaluation, both checkpoint conventions.",
            "",
            "**Boundary.** Action rights stay partitioned in both arms. This prices the",
            "partition of information, reward and optimisation, not decentralisation entire.",
            "**MUST NOT** state a direction. The two arms agree to five decimal places on the",
            "mean and on the median at the selected checkpoint, and no seed separates.",
            "**MUST NOT** carry over the 4,000-episode version of this claim, where mean and",
            "median disagreed and one seed of six was significant. That seed's centralised run",
            "measured 0.00263 while every other run sat at 0.00000-0.00066; at 12,000 episodes",
            "it measures 0.00000. It was an unconverged run, not a cost of centralisation.",
            "**MUST NOT** read the final-update column as a federation effect: selection helps",
            "the federated arm and is inert for the pooled one, which is a checkpoint result.", ""]
else:
    out += ["## C4 — Federating information, reward and optimisation costs nothing measurable", "",
            f"**NOT YET AVAILABLE** -- {len(LAD)} of 4 ladder measurements at 12,000 episodes.", ""]

# --- Undertraining ---------------------------------------------------------------------------
out += ["## C5 — The competence-floor exclusions are undertrained, not broken", "",
        "| cell (seed 2) | 4,000 ep wr / learned | 12,000 ep wr / learned | myopic |",
        "|---|---|---|---|"]
for p in sorted((TR / "federation").glob("*_long_s2.json")):
    cell = p.name.replace("_long_s2.json", "")
    d12 = json.loads(p.read_text())
    d4 = json.loads((TR / "sweep" / f"{cell}_s2.json").read_text())
    out.append(f"| {cell} | {wr(d4):.3f} / {d4['arms']['learned']['success']:.3f} | "
               f"**{wr(d12):.3f} / {d12['arms']['learned']['success']:.3f}** | "
               f"{d12['arms']['greedy_uncertainty']['success']:.3f} |")
out += ["",
        "All seven pass the floor and all seven beat the myopic rule when converged. Halving the",
        "learning rate instead makes them worse (0.519 -> 0.206, 0.345 -> 0.177).",
        "**MUST NOT** substitute these into any sweep table. The sweep holds the training budget",
        "fixed at 4,000 episodes across all twenty cells; mixing budgets between cells would",
        "confound the axis being varied. Report them beside the sweep as a limitation of it.", ""]

# --- RQ2: the partial oracle ------------------------------------------------------------------
# Written before the deterministic grid finished building, so it degrades to a note rather
# than raising when the files are absent -- CLAIMS.md must stay regenerable at any moment.
RATES = [1.00, 0.95, 0.90, 0.85, 0.80, 0.70, 0.50]
WIN_AT_OR_BELOW = 0.90
grid = {}
for r in RATES:
    for s in (0, 1, 2):
        p = TR / "power" / f"xfer_rho{r:.2f}_s{s}.json"
        if p.exists():
            d = json.loads(p.read_text())
            grid[(r, s)] = (d[0] if isinstance(d, list) else d)

out += ["## C6 — Training under a partial oracle transfers to sampled evidence", ""]
if len(grid) < len(RATES) * 3:
    out += [f"**NOT YET AVAILABLE** -- {len(grid)} of {len(RATES) * 3} cells present in",
            "`thesis_results/power/`. Chapter 4 may assert nothing here until the grid is",
            "complete. Do not fill the gap from `docs/FINDINGS_TRANSFER_2026_09_02.md`; that",
            "note quotes the pre-fix grid.", ""]
else:
    out += ["| $\\rho$ | learned | myopic | paired $\\Delta$ | seed SE | ahead beyond 2 SE |",
            "|---|---|---|---|---|---|"]
    for r in RATES:
        cells = [grid[(r, s)] for s in (0, 1, 2)]
        dl = np.array([c["paired"]["learned-greedy"]["delta"] for c in cells])
        sig = sum(c["paired"]["learned-greedy"]["delta"] < 0
                  and abs(c["paired"]["learned-greedy"]["delta"])
                  > 2 * c["paired"]["learned-greedy"]["se"] for c in cells)
        out.append(f"| {r:.2f} | {np.mean([c['means']['learned']['hard'] for c in cells]):.5f} "
                   f"| {np.mean([c['means']['greedy']['hard'] for c in cells]):.5f} "
                   f"| {dl.mean():+.5f} | {dl.std(ddof=1) / np.sqrt(3):.5f} | {sig}/3 |")
    lo = [c for (r, _), c in grid.items() if r <= WIN_AT_OR_BELOW]
    hi = [c for (r, _), c in grid.items() if r > WIN_AT_OR_BELOW]

    def sig_ahead(cs):
        return sum(c["paired"]["learned-greedy"]["delta"] < 0
                   and abs(c["paired"]["learned-greedy"]["delta"])
                   > 2 * c["paired"]["learned-greedy"]["se"] for c in cs)

    out += ["",
            f"* $\\rho \\le {WIN_AT_OR_BELOW}$: {sum(c['paired']['learned-greedy']['delta'] < 0 for c in lo)}"
            f"/{len(lo)} cells ahead by sign, **{sig_ahead(lo)}/{len(lo)} ahead beyond 2 SE**",
            f"* $\\rho > {WIN_AT_OR_BELOW}$: {sum(c['paired']['learned-greedy']['delta'] < 0 for c in hi)}"
            f"/{len(hi)} ahead by sign, **{sig_ahead(hi)}/{len(hi)} ahead beyond 2 SE**", ""]
    out += [
        "**Boundary.** One cell -- $k_v=8$, four agents, budget 70, `factored` backend. The",
        "curve is monotone and saturating over the swept range; no interior optimum is claimed",
        "and no floor, since $\\rho < 0.50$ was not measured. The myopic column is identical at",
        "every rate by construction: the baseline arms are the same per-episode vectors reused",
        "across rates, which is an exact pairing and a check that the comparison did not move.",
        "**MUST NOT** say \"no high-rate cell beats the myopic rule\" without the 2 SE",
        "qualifier. Two of the six high-rate cells are numerically ahead and both are inside",
        "noise; the claim is about significance, not sign, and an earlier draft of the findings",
        "note blurred the two.",
        "**MUST NOT** quote any number from `results/power/rho/` outside `deterministic/`. The",
        "pre-fix grid was scored without a seeded torch RNG and is not reproducible.", ""]

path = TR / "CLAIMS.md"
path.write_text("\n".join(out))
print(f"wrote {path.relative_to(ROOT)}: {len(out)} lines")


def build_appendix():
    """thesis/Appendix.tex -- the excluded runs, named, with what retraining did to them.

    Section 4.1 cites this. Generated rather than typed so the list cannot drift from the
    competence floor that produced it.
    """
    rows = []
    for p in sorted((TR / "sweep").glob("k*_s*.json")):
        d = json.loads(p.read_text())
        if wr(d) >= FLOOR:
            continue
        cell = p.stem.rsplit("_s", 1)[0]
        long = TR / "federation" / f"{cell}_long_s2.json"
        retrained = json.loads(long.read_text()) if long.exists() else None
        rows.append((cell, d.get("seed"), wr(d), d["arms"]["learned"]["success"],
                     wr(retrained) if retrained else None,
                     retrained["arms"]["learned"]["success"] if retrained else None,
                     d["arms"]["greedy_uncertainty"]["success"]))

    out = [r"\appendix", "", r"\chapter{Excluded Runs} \label{app:excluded}", "",
           "Every run falling below the competence floor of \\S\\ref{sec:meth_gate}, with what",
           "the same configuration reaches when trained to $12{,}000$ episodes instead of",
           "$4{,}000$. The retrained runs appear nowhere in the sweep tables of",
           "Chapter~\\ref{Chap4}, which hold the training budget fixed across all cells.", "",
           r"\begin{table}[htbp]", r"\centering",
           r"\caption{The seven excluded runs. Per-window recovery rate and joint recovery, "
           r"at the sweep's budget and at three times it.}",
           r"\label{tab:excluded}", r"\begin{tabular}{llcccccc}", r"\toprule",
           r"Cell & Seed & \multicolumn{2}{c}{4{,}000 episodes} & "
           r"\multicolumn{2}{c}{12{,}000 episodes} & Myopic \\",
           r"\cmidrule(lr){3-4}\cmidrule(lr){5-6}",
           r" & & window & joint & window & joint & joint \\", r"\midrule"]
    for cell, seed, w4, l4, w12, l12, g in rows:
        cellname = cell.replace("_", r"\_")
        tail = (f"{w12:.3f} & {l12:.3f}" if w12 is not None else "--- & ---")
        out.append(f"\\texttt{{{cellname}}} & {seed} & {w4:.3f} & {l4:.3f} & {tail} & {g:.3f} \\\\")
    out += [r"\bottomrule", r"\end{tabular}", r"\end{table}", "",
            f"All {len(rows)} excluded runs are seed 2, and all are at $k_v=12$. Every one clears",
            "the floor when retrained, and every one finishes above the myopic rule on its own",
            "cell. The floor therefore removes runs that had not finished learning rather than",
            "cells that cannot be learned.", ""]
    # DISABLED 2 Sep 22:5x. This wrote thesis/Appendix.tex, and so does
    # scripts/build_appendix.py -- which generates FOUR appendices including this one. Whichever
    # ran last won, so running build_claims.py after build_appendix.py silently deleted the
    # Training Budget, Checkpoint Selection and Supporting Ablations appendices and left two
    # dangling \ref{} in Chapter 4 rendering as "??". Found by a label/ref audit, not by either
    # script failing. build_appendix.py is the single owner of that file; this function stays
    # only so the history of the collision is legible.
    raise SystemExit("build_claims.py no longer writes thesis/Appendix.tex; "
                     "run scripts/build_appendix.py for it")


# build_appendix()  # see above: scripts/build_appendix.py owns thesis/Appendix.tex
