"""Generate the distributional-and-mechanistic robustness tables from the run files.

WHAT THIS MEASURES. One policy fleet, evaluated under generators it never trained on: the
noise SHAPE is changed (Gaussian, uniform, Student-t with 3 df) and the parent-to-child
MECHANISM is changed (linear, saturating, V-shaped). Every corner is the same checkpoints,
the same 200 paired episodes per seed, the same three seeds; only the generator moves.

TWO TABLES, TWO PLACES. The compact one goes inline in Chapter 4's robustness section --
it is that section's only float, so it carries the result. The per-seed one goes in the
appendix, because the spread over three seeds is what shows no corner is being carried by
a single lucky run, and that belongs where a reader can check it rather than in the body.

Every number here is recomputed from the per-episode vectors in the run files. Nothing is
read from a summary field, and the corners are refused rather than partially reported if a
seed is missing -- a five-row table with one three-seed row and one two-seed row invites a
comparison that is not being made.

    .venv/bin/python scripts/build_robustness.py
"""
from __future__ import annotations
import json
import pathlib

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[1]

# The corners, in the order they are reported: the linear-Gaussian reference first, then one
# change at a time, then both at once, then the adversarial mechanism.
#
# The reference corner is the SAME policies evaluated under the SAME protocol, from the
# stored transfer set. It is what licenses reading every other row as an effect of the
# generator rather than of the evaluation.
CORNERS = [
    ("Gaussian", "linear", "linear-Gaussian reference",
     "results/power/rho/deterministic/xfer_rho0.50_s?.json"),
    ("uniform", "linear", "bounded, light-tailed",
     "results/noisedist/rho050_uniform_s?.json"),
    ("Student-$t_3$", "linear", "heavy-tailed",
     "results/noisedist/rho050_t3_s?.json"),
    ("Gaussian", "saturating", "nonlinear, monotone",
     "results/noisedist/rho050_gaussian_tanh_s?.json"),
    ("Student-$t_3$", "saturating", "both at once",
     "results/noisedist/rho050_t3_tanh_s?.json"),
    ("Gaussian", "V-shaped", "adversarial",
     "results/noisedist/rho050_gaussian_vshape_s?.json"),
]


def load():
    """One record per corner, or a short list if a corner is not fully measured."""
    rows = []
    for noise, mech, note, pat in CORNERS:
        fs = sorted(ROOT.glob(pat))
        if len(fs) != 3:
            continue
        es = [json.loads(f.read_text())[0] for f in fs]
        # RECOMPUTED from the per-episode vectors rather than read from "means".
        per = {arm: [float(np.mean(e["rows"][arm]["hard"])) for e in es]
               for arm in ("learned", "greedy", "random_vary")}
        ahead = sum(1 for e in es
                    if e["paired"]["learned-greedy"]["significant"]
                    and e["paired"]["learned-greedy"]["delta"] < 0)
        rows.append(dict(noise=noise, mech=mech, note=note, per=per, n=len(es),
                         ahead=ahead, seeds=[e["seed"] for e in es],
                         L=float(np.mean(per["learned"])),
                         G=float(np.mean(per["greedy"])),
                         R=float(np.mean(per["random_vary"])),
                         delta=[e["paired"]["learned-greedy"]["delta"] for e in es],
                         se=[e["paired"]["learned-greedy"]["se"] for e in es]))
    return rows


def _check(rows):
    """Refuse to emit a table whose corners were not measured under one protocol."""
    keys = {(e["episodes"], e["checkpoint"], e["eval_evidence"])
            for noise, mech, note, pat in CORNERS
            for f in sorted(ROOT.glob(pat))
            for e in [json.loads(f.read_text())[0]]}
    if len(keys) != 1:
        raise SystemExit(f"corners disagree on evaluation protocol: {sorted(keys)}")
    return keys.pop()


def compact(rows, protocol):
    episodes, checkpoint, evidence = protocol
    body = []
    for r in rows:
        lead = f"{r['G'] / r['L']:.2f}" if r["L"] > 0 else "---"
        body.append(f"{r['noise']} & {r['mech']} & {r['L']:.5f} & {r['G']:.5f} & "
                    f"{r['R']:.5f} & ${lead}\\times$ & {r['ahead']}/{r['n']} \\\\")
    return "\n".join([
        "% Generated by scripts/build_robustness.py. Do not edit by hand.",
        "% Chapter 4 inputs this file; regenerating it cannot touch prose.",
        "",
        r"\begin{table}[htbp]",
        r"\centering",
        f"\\caption[Robustness across generator corners]{{Pooled SHD on committed marks under generators the policies did not "
        f"train on, {episodes} paired episodes per seed, three seeds per corner. Lower is "
        f"better. The last column counts seeds where the learned arm leads the myopic one "
        f"by more than two standard errors.}}",
        r"\label{tab:robust}",
        r"\begin{tabular}{llccccc}",
        r"\toprule",
        r"Noise & Mechanism & Learned & Myopic & Random & Myopic/learned & Ahead \\",
        r"\midrule",
        *body,
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ])


def per_seed(rows):
    """The appendix table: every seed of every corner, and the paired difference."""
    body = []
    for r in rows:
        for i, sd in enumerate(r["seeds"]):
            first = f"{r['noise']} & {r['mech']}" if i == 0 else " & "
            body.append(
                f"{first} & {sd} & {r['per']['learned'][i]:.5f} & "
                f"{r['per']['greedy'][i]:.5f} & {r['per']['random_vary'][i]:.5f} & "
                f"${r['delta'][i]:+.5f} \\pm {r['se'][i]:.5f}$ \\\\")
        if r is not rows[-1]:
            body.append(r"\addlinespace")
    return body


def main() -> int:
    rows = load()
    missing = [f"{n}/{m} ({len(sorted(ROOT.glob(pat)))}/3 seeds)"
               for n, m, _, pat in CORNERS if len(sorted(ROOT.glob(pat))) != 3]
    if missing:
        print(f"  !! PENDING, not emitted: {', '.join(missing)}")
        return 1
    protocol = _check(rows)
    out = ROOT / "thesis/Robustness.tex"
    out.write_text(compact(rows, protocol))
    print(f"wrote {out.relative_to(ROOT)}: {len(rows)} corners, protocol {protocol}")
    for r in rows:
        print(f"  {r['noise']:14s} {r['mech']:11s} learned {r['L']:.5f}  "
              f"myopic {r['G']:.5f}  random {r['R']:.5f}  ahead {r['ahead']}/{r['n']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
