"""Emit Chapter 4's axis tables at 12,000 episodes, both checkpoint conventions.

WHY A SEPARATE FILE FROM THE CHAPTER. `build_results_skeleton.py` writes the whole chapter and
would destroy the prose in it. This writes `thesis/Tables12k.tex`, which the chapter `\\input`s,
so regenerating tables after a measurement lands can never touch a sentence.

WHY BOTH CONVENTIONS. At 12,000 episodes neither is safe alone: of 21 seeds measured both ways,
8 disagree by more than a factor of three, 5 with the selected checkpoint worse and 3 with the
final worse (`FINDINGS_CHECKPOINT_TAIL_2026_09_02.md`). Reporting one column would be choosing a
convention that fails on roughly a fifth of seeds in an unpredictable direction.

A cell whose measurement has not landed emits a PENDING row rather than a blank or a plausible
number. Two silent failures today came from code that improvised instead of refusing.
"""
from __future__ import annotations
import glob, json, os, pathlib, re
import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[1]
CELL = re.compile(r"k(\d+)s(\d+)n(\d+)b(\d+)")
PRE = {"k12s50n05b150": "results/longcheck/shd_n05_12k.json",
       "k12s75n04b150": "results/longcheck/shd_s75_12k.json",
       "k12s50n08b150": "results/longcheck/shd_n08_12k.json",
       "k12s50n10b150": "results/longcheck/shd_n10_12k.json"}
# k=20 and k=30 trained at 12,000 in the original sweep and were measured there. Verified
# against their configs: train_episodes = 12000 for both, 4000 for every other cell on this
# axis. Sourced from results/rerows, not results/ckpt -- the ckpt/ set predates the evaluation
# RNG being seeded (2 Sep 21:15) and does not reproduce.
LEGACY = {"k20s50n04b150": ("results/rerows/k20_best.json", "results/rerows/k20_final.json"),
          "k30s50n04b150": ("results/rerows/k30_best.json", "results/rerows/k30_final.json")}

AXES = [("Window size", "k", r"$k_v$", lambda c: c["s"] == 50 and c["n"] == 4 and c["b"] == 150),
        ("Federation size", "n", r"$K$", lambda c: c["k"] == 12 and c["s"] == 50 and c["b"] == 150),
        ("Contended fraction", "s", r"$\sigma$", lambda c: c["k"] == 12 and c["n"] == 4 and c["b"] == 150),
        ("Budget multiplier", "b", r"$\beta$", lambda c: c["k"] == 12 and c["s"] == 50 and c["n"] == 4)]


def paths(cell):
    if cell in LEGACY:
        return (ROOT / LEGACY[cell][0], ROOT / LEGACY[cell][1])
    best = ROOT / PRE.get(cell, f"results/sweep12k/shd/{cell}.json")
    return (best, ROOT / f"results/sweep12k/shd_final/{cell}.json")


def stats(path, arm="learned"):
    if not path.exists():
        return None
    d = json.loads(path.read_text())
    v = [e["means"][arm]["hard"] for e in d]
    return (np.mean(v), len(v)) if v else None


def cells_on(axis_keep):
    out = {}
    for p in glob.glob(str(ROOT / "results/sweep/oracle/k*_s*.json")):
        m = CELL.match(os.path.basename(p))
        if not m:
            continue
        c = dict(k=int(m[1]), s=int(m[2]), n=int(m[3]), b=int(m[4]))
        if axis_keep(c):
            out[m.group(0)] = c
    return out


def recovery(cell, budget):
    """Joint recovery rate, both arms, at a training budget. The myopic arm does not train,
    so its column is identical at 4,000 and 12,000 -- which is what makes the comparison
    like-for-like rather than two different experiments."""
    d = "results/sweep12k" if budget == 12000 else "results/sweep/oracle"
    fs = sorted(glob.glob(str(ROOT / d / f"{cell}_s?.json")))
    if not fs:
        return None
    L = np.mean([json.loads(open(f).read())["arms"]["learned"]["success"] for f in fs])
    M = np.mean([json.loads(open(f).read())["arms"]["greedy_uncertainty"]["success"] for f in fs])
    return L, M, len(fs)


def favour(path):
    """Seeds on which the learned arm is ahead, and seeds on which it is ahead beyond 2 SE."""
    if not path.exists():
        return None
    d = json.loads(path.read_text())
    return (sum(1 for e in d if e["paired"]["learned-greedy"]["delta"] < 0),
            sum(1 for e in d if e["paired"]["learned-greedy"]["delta"] < 0
                and e["paired"]["learned-greedy"]["significant"]), len(d))


def main() -> int:
    parts = ["% Generated by scripts/build_tables12k.py. Do not edit by hand.",
             "% Chapter 4 inputs this file; regenerating it cannot touch prose.", ""]
    pending = []
    for title, key, sym, keep in AXES:
        found = cells_on(keep)
        rows = []
        for cell, c in sorted(found.items(), key=lambda kv: kv[1][key]):
            x = c[key] / 100 if key in ("s", "b") else c[key]
            bp, fp = paths(cell)
            b, f = stats(bp), stats(fp)
            g = stats(bp, "greedy") if bp.exists() else None
            if b is None or f is None or g is None:
                pending.append(cell)
                rows.append(f"{x:g} & \\multicolumn{{7}}{{c}}{{\\emph{{pending}}}} \\\\")
                continue
            r12 = recovery(cell, 12000)
            fav = favour(bp)
            rec = f"{r12[0]:.3f} & {r12[1]:.3f}" if r12 else "--- & ---"
            fv = f"{fav[0]}/{fav[2]} & {fav[1]}/{fav[2]}" if fav else "--- & ---"
            rows.append(f"{x:g} & {b[0]:.5f} & {f[0]:.5f} & {g[0]:.5f} & {rec} & {fv} \\\\")
        parts.append("\n".join([
            r"\begin{table}[htbp]", r"\centering",
            f"\\caption{{{title} axis at $12{{,}}000$ episodes. Structural distance of the "
            r"pooled global graph on committed marks, 200 paired episodes per seed, at both "
            r"checkpoint conventions.}",
            f"\\label{{tab:12k_{key}}}", r"\begin{tabular}{rcccccrr}", r"\toprule",
            f"{sym} & \\multicolumn{{3}}{{c}}{{SHD}} & \\multicolumn{{2}}{{c}}{{Joint recovery}} "
            r"& \multicolumn{2}{c}{Seeds ahead} \\",
            r"\cmidrule(lr){2-4}\cmidrule(lr){5-6}\cmidrule(lr){7-8}",
            r" & selected & final & myopic & learned & myopic & any & $2$\,SE \\",
            r"\midrule", *rows, r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]))

    # THE HEADLINE TABLE. Every cell, joint recovery at both budgets, myopic arm shared.
    # The myopic column is computed once because that arm does not train: it is the same
    # policy at both budgets, which is what makes this a controlled comparison rather than
    # two separate experiments.
    hrows, w4, w12, flips = [], 0, 0, 0
    cells12 = sorted({q.stem for q in (ROOT / "results/sweep12k/shd_final").glob("*.json")})
    for cell in cells12:
        r4, r12 = recovery(cell, 4000), recovery(cell, 12000)
        if not r4 or not r12:
            continue
        M = r4[1]
        w4 += r4[0] > M
        w12 += r12[0] > M
        flips += (r4[0] > M) != (r12[0] > M)
        mark = r"$\rightarrow$" if (r4[0] > M) != (r12[0] > M) else ""
        hrows.append(f"\\texttt{{\\scriptsize {cell.replace('_', chr(92)+'_')}}} & {r4[0]:.3f} & "
                     f"{r12[0]:.3f} & {M:.3f} & {mark} \\\\")
    parts.append("\n".join([
        r"\begin{table}[htbp]", r"\centering",
        r"\caption{Joint recovery rate for every cell of the sweep at both training budgets. "
        r"The myopic column is one number per cell because that arm does not train, so the "
        r"same policy is scored at both budgets. An arrow marks a cell where the winner "
        r"changes.}",
        r"\label{tab:12k_headline}", r"\begin{tabular}{lcccc}", r"\toprule",
        r"Cell & Learned, $4{,}000$ & Learned, $12{,}000$ & Myopic & \\",
        r"\midrule", *hrows, r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]))
    print(f"headline: learned ahead in {w4}/{len(hrows)} cells at 4,000 and "
          f"{w12}/{len(hrows)} at 12,000; {flips} cells change winner")

    out = ROOT / "thesis/Tables12k.tex"
    out.write_text("\n".join(parts))
    print(f"wrote {out.relative_to(ROOT)}: 4 axis tables")
    if pending:
        print(f"PENDING measurement, {len(set(pending))} cells: {sorted(set(pending))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
