"""Generate `thesis_results/CLAIMS.md`: the sentence-level facts Chapter 4 may assert.

WHY. The ledger is a working document and has been wrong twice: section 2.2 quoted a
share-of-ceiling as a raw rate, and section 1.3 reported an asymmetry that a larger
re-measurement retracted. Chapter 4 needs a source that is derived from the data files rather
than maintained by hand, and that carries the boundary of each claim next to the number.

Every figure below is computed at generation time from `thesis_results/`. The MUST NOT lines
are hand-maintained, because a retraction is a judgement and not a computation -- they are the
part to read before writing a sentence.
"""
from __future__ import annotations
import glob, json, pathlib
import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[1]
TR = ROOT / "thesis_results"
FLOOR, TAIL = 0.70, 10


def wr(d):
    t = [h.get("window_rate", 0.0) for h in (d.get("history") or [])[-TAIL:]]
    return sum(t) / len(t) if t else 0.0


def sweep(pattern):
    return [json.loads(p.read_text()) for p in sorted((TR / "sweep").glob(pattern))]


def ck(k, which):
    return json.loads((TR / "checkpoint" / f"k{k:02d}_{which}.json").read_text())


def fed(name):
    return [json.loads(p.read_text()) for p in sorted((TR / "federation").glob(name))]


out = ["# Claims — what Chapter 4 may assert, with the number and its boundary", "",
       "Generated by `scripts/build_claims.py` from `thesis_results/`. **Do not edit the",
       "numbers by hand.** The MUST NOT lines are hand-maintained and are the important part.",
       "", "Regenerate after `scripts/collect_thesis_results.py`.", ""]

# --- RQ1: crossover -----------------------------------------------------------------------
out += ["## C1 — The advantage changes sign between $k_v=8$ and $k_v=12$", "",
        "| $k_v$ | recovery L | recovery M | SHD L (selected) | SHD L (final) | SHD M |",
        "|---|---|---|---|---|---|"]
for k in (4, 8, 12, 20, 30):
    s = sweep(f"k{k:02d}s50n04b150_s*.json")
    rl = np.mean([r["arms"]["learned"]["success"] for r in s])
    rm = np.mean([r["arms"]["greedy_uncertainty"]["success"] for r in s])
    b = np.mean([r["means"]["learned"]["hard"] for r in ck(k, "best")])
    f = np.mean([r["means"]["learned"]["hard"] for r in ck(k, "final")])
    m = np.mean([r["means"]["greedy"]["hard"] for r in ck(k, "best")])
    out.append(f"| {k} | {rl:.3f} | {rm:.3f} | {b:.5f} | {f:.5f} | {m:.5f} |")
out += ["",
        "**Boundary.** Recovery rate is the final policy; SHD is reported at both checkpoints.",
        "SHD is measured under a seeded evaluation (2 Sep 22:xx). The myopic column reproduces",
        "the pre-fix measurement to five decimals at every $k_v$; the learned column moved by",
        "0.00 to 0.99 paired SE. `FINDINGS_DETERMINISM_2026_09_02.md`",
        "At $k_v=30$ the paired per-seed differences are -0.00009 +/- 0.00034, -0.00040 +/-",
        "0.00008 and -0.00005 +/- 0.00021: **one seed of three separates**, two are",
        "indistinguishable. The earlier reading of this line said two of three; that was",
        "measured before the evaluation RNG was seeded and is withdrawn.",
        "**MUST NOT** quote a ratio of means at $k_v=30$; one seed carries the whole of it.",
        "**MUST NOT** read this axis as monotone in $k_v$, and MUST NOT say the sweep holds the",
        "training budget fixed. It does not. Verified from `config.train_episodes` over all 60",
        "runs: 18 cells at 4,000 episodes and 2 at 12,000, and the two at 12,000 are",
        "`k20s50n04b150` and `k30s50n04b150` -- the two that carry the headline. Window size and",
        "training budget are perfectly collinear across the last two points.",
        "(FINDINGS_WINDOW_BUDGET_CONFOUND_2026_09_02.md, agent C.)",
        "**WHAT SURVIVES, and it is more than that note allows.** $k_v=4$, $8$ and $12$ are all",
        "at 4,000 episodes, so the recovery gap over those three points -- -0.075, -0.025, +0.058",
        "-- is a clean within-budget comparison, and it contains the sign change. The monotone",
        "trend and the crossover may both be stated over $k_v \\le 12$. What may NOT be done is",
        "extend the trend to $k_v=20$ and $30$, where the budget triples with the window.",
        "The uniform-budget version of this axis is `tab:12k_k` in thesis/Tables12k.tex, which",
        "reports all five windows at 12,000 episodes.",
        "**MUST NOT** describe $k_v=8$ as favouring either arm. Per seed the paired differences",
        "are -0.00016 (ns), -0.00059 (SIG, learned ahead) and +0.00096 (ns): the seeds disagree",
        "and the mean is carried by seed 2. The crossover is between 8 and 12, and 8 is the",
        "cell where it is ambiguous rather than the last cell the myopic rule wins.", ""]

# --- RQ1: agent count ---------------------------------------------------------------------
out += ["## C2 — The advantage reverses as agents are added", "",
        "| $K$ | SHD L | SHD M | ratio | ratio excl. seed 2 | seeds |", "|---|---|---|---|---|---|"]
for n in (2, 3, 4, 5, 8, 10):
    rows = [r for r in sweep(f"k12s50n{n:02d}b150_s*.json") if wr(r) >= FLOOR]
    L = [r["arms"]["learned"]["global_hard_shd"] for r in rows]
    G = [r["arms"]["greedy_uncertainty"]["global_hard_shd"] for r in rows]
    S = [r.get("seed") for r in rows]
    L2 = [v for v, s in zip(L, S) if s != 2]
    G2 = [v for v, s in zip(G, S) if s != 2]
    r2 = (np.mean(L2) / np.mean(G2)) if L2 else float("nan")
    out.append(f"| {n} | {np.mean(L):.5f} | {np.mean(G):.5f} | {np.mean(L)/np.mean(G):.2f} | "
               f"{r2:.2f} | {len(rows)} |")
out += ["",
        "**Boundary.** At $K=5$ the reversal is one seed: 1.65 with all seeds, 0.25 without.",
        "State the reversal as beginning at eight agents. Both figures must appear.",
        "**UNRESOLVED 2 Sep 10:5x. A confound was found; see FINDINGS_AGENT_COUNT_2026_09_02.md.**",
        "The `seed 2 converged` column compares a 4,000-episode FINAL policy against a",
        "12,000-episode FINAL policy, and the final policy degrades on long runs. Re-measuring",
        "both from the selected checkpoint. Quote neither column until that lands.",
        "Earlier note, now suspect: `k12s50n08b150_s2` passed the floor at",
        "0.838 but was unconverged. Retrained at 12,000 episodes its SHD goes 0.00290 -> 0.00005,",
        "and the K=8 ratio goes 4.24 (as run) -> 1.82 (excluding it) -> **0.89 (with it",
        "converged)**. At eight agents the learned policy is BETTER than the myopic rule once",
        "trained to convergence, and the reversal there is a training-budget artefact.",
        "`k12s50n10b150_s2` is still retraining. Seed 3 at eight agents and sigma=0.25 also",
        "went 0.632 FAIL -> 1.000 PASS with learned 1.000 against myopic 0.860.",
        "**MUST NOT** state an agent-count reversal until K=10 lands. If it also converges away,",
        "the honest claim is about SAMPLE EFFICIENCY under contention, not achievable accuracy:",
        "at a fixed 4,000-episode budget the learned policy degrades as agents are added, and",
        "given adequate training the degradation does not survive.",
        "**MUST NOT** claim the myopic rule improves across this axis. Per-pair SHD divides by",
        "`global_pairs`, which runs 117 -> 525; in raw counts the myopic arm is close to flat.", ""]

# --- RQ1: pair class ----------------------------------------------------------------------
pc = json.loads((ROOT / "results/shd_by_class_200.json").read_text())
out += ["## C3 — The learned advantage is entirely on scored pairs", "",
        "| arm | private-incident | shared-shared |", "|---|---|---|"]
for arm in ("learned", "greedy", "random"):
    out.append(f"| {arm} | {np.mean([e['arms'][arm]['private_incident'] for e in pc]):.5f} | "
               f"{np.mean([e['arms'][arm]['shared_shared'] for e in pc]):.5f} |")
out += ["", f"6 runs, 200 episodes, `_best.pt`. "
        f"{sum(e['arms']['learned']['n_private'] for e in pc):,} private-incident and "
        f"{sum(e['arms']['learned']['n_shared'] for e in pc):,} shared-shared observations.",
        "**MUST NOT** write the reward-alignment asymmetry (ledger 1.3). RETRACTED.", ""]

# The retraction above was justified with 'shared-shared error is 0.00000 for both arms,
# maximum across all six runs'. True of those six (k=20 and k=30) and NOT true in general:
# on the agent-count axis the learned arm is nonzero on the least-converged seeds. Measured
# properly at 12,000 episodes the effect is real in direction and negligible in size, which
# is a better defence of the retraction than a blanket zero that does not hold everywhere.
pc12 = ROOT / "results/shd_by_class_naxis_12k.json"
if pc12.exists():
    n12 = json.loads(pc12.read_text())
    obs = sum(e["arms"]["learned"]["n_shared"] for e in n12)
    errL = sum(e["arms"]["learned"]["shared_shared"] * e["arms"]["learned"]["n_shared"] for e in n12)
    errG = sum(e["arms"]["greedy"]["shared_shared"] * e["arms"]["greedy"]["n_shared"] for e in n12)
    zero = sum(1 for e in n12 if e["arms"]["learned"]["shared_shared"] == 0)
    out += ["### C3a — the same question at 12,000 episodes, on the agent-count axis", "",
            f"* {obs:,} shared-shared pair observations over {len(n12)} converged runs",
            f"* learned commits **{errL:.0f}** errors on them; myopic commits **{errG:.0f}**",
            f"* {zero} of {len(n12)} runs are at exactly zero; every error sits in one cell",
            "",
            "**Correction to C3's justification.** 'Zero for both arms' holds for the six k=20",
            "and k=30 runs and does NOT hold on the agent-count axis. The asymmetry exists and",
            "is in the predicted direction. It is also 11 errors in 27,000 observations, so it",
            "cannot carry a claim about the policy neglecting what it is not paid for.",
            "**MUST NOT** revive ledger 1.3 from this. **MUST NOT** state the blanket zero.", ""]

# --- RQ3 ------------------------------------------------------------------------------------
A = fed("shd_A.json") + fed("shd_A_s345.json")
E = fed("shd_E.json") + fed("shd_E_s345.json")
LA = [x["means"]["learned"]["hard"] for e in A for x in e]
LE = [x["means"]["learned"]["hard"] for e in E for x in e]
G = [x["means"]["greedy"]["hard"] for e in A for x in e]
d = np.array(LA) - np.array(LE)
se = d.std(ddof=1) / np.sqrt(len(d))
out += ["## C4 — Federating information, reward and optimisation costs nothing measurable", "",
        f"* federated SHD mean {np.mean(LA):.5f}, median {np.median(LA):.5f}",
        f"* centralised SHD mean {np.mean(LE):.5f}, median {np.median(LE):.5f}",
        f"* myopic on the same episodes {np.mean(G):.5f}",
        f"* **paired federated - centralised over {len(d)} seeds: {d.mean():+.5f} +/- {se:.5f}"
        f" ({'inside' if abs(d.mean()) <= 2*se else 'outside'} 2 SE)**", "",
        "**Boundary.** Action rights stay partitioned in both arms. This is the cost of",
        "partitioning information, reward and optimisation, not of decentralisation entire.",
        "**MUST NOT** state a direction: mean and median disagree on which arm leads.", ""]

# --- Undertraining ---------------------------------------------------------------------------
out += ["## C5 — The competence-floor exclusions are undertrained, not broken", "",
        "| cell (seed 2) | 4,000 ep wr / learned | 12,000 ep wr / learned | myopic |",
        "|---|---|---|---|"]
for p in sorted((TR / "federation").glob("*_long_s2.json")):
    cell = p.name.replace("_long_s2.json", "")
    d12 = json.loads(p.read_text())
    d4 = json.loads((TR / "sweep" / f"{cell}_s2.json").read_text())
    out.append(f"| {cell} | {wr(d4):.3f} / {d4['arms']['learned']['success']:.3f} | "
               f"**{wr(d12):.3f} / {d12['arms']['learned']['success']:.3f}** | "
               f"{d12['arms']['greedy_uncertainty']['success']:.3f} |")
out += ["",
        "All seven pass the floor and all seven beat the myopic rule when converged. Halving the",
        "learning rate instead makes them worse (0.519 -> 0.206, 0.345 -> 0.177).",
        "**MUST NOT** substitute these into any sweep table. The sweep holds the training budget",
        "fixed at 4,000 episodes across all twenty cells; mixing budgets between cells would",
        "confound the axis being varied. Report them beside the sweep as a limitation of it.", ""]

# --- RQ2: the partial oracle ------------------------------------------------------------------
# Written before the deterministic grid finished building, so it degrades to a note rather
# than raising when the files are absent -- CLAIMS.md must stay regenerable at any moment.
RATES = [1.00, 0.95, 0.90, 0.85, 0.80, 0.70, 0.50]
WIN_AT_OR_BELOW = 0.90
grid = {}
for r in RATES:
    for s in (0, 1, 2):
        p = TR / "power" / f"xfer_rho{r:.2f}_s{s}.json"
        if p.exists():
            d = json.loads(p.read_text())
            grid[(r, s)] = (d[0] if isinstance(d, list) else d)

out += ["## C6 — Training under a partial oracle transfers to sampled evidence", ""]
if len(grid) < len(RATES) * 3:
    out += [f"**NOT YET AVAILABLE** -- {len(grid)} of {len(RATES) * 3} cells present in",
            "`thesis_results/power/`. Chapter 4 may assert nothing here until the grid is",
            "complete. Do not fill the gap from `docs/FINDINGS_TRANSFER_2026_09_02.md`; that",
            "note quotes the pre-fix grid.", ""]
else:
    out += ["| $\\rho$ | learned | myopic | paired $\\Delta$ | seed SE | ahead beyond 2 SE |",
            "|---|---|---|---|---|---|"]
    for r in RATES:
        cells = [grid[(r, s)] for s in (0, 1, 2)]
        dl = np.array([c["paired"]["learned-greedy"]["delta"] for c in cells])
        sig = sum(c["paired"]["learned-greedy"]["delta"] < 0
                  and abs(c["paired"]["learned-greedy"]["delta"])
                  > 2 * c["paired"]["learned-greedy"]["se"] for c in cells)
        out.append(f"| {r:.2f} | {np.mean([c['means']['learned']['hard'] for c in cells]):.5f} "
                   f"| {np.mean([c['means']['greedy']['hard'] for c in cells]):.5f} "
                   f"| {dl.mean():+.5f} | {dl.std(ddof=1) / np.sqrt(3):.5f} | {sig}/3 |")
    lo = [c for (r, _), c in grid.items() if r <= WIN_AT_OR_BELOW]
    hi = [c for (r, _), c in grid.items() if r > WIN_AT_OR_BELOW]

    def sig_ahead(cs):
        return sum(c["paired"]["learned-greedy"]["delta"] < 0
                   and abs(c["paired"]["learned-greedy"]["delta"])
                   > 2 * c["paired"]["learned-greedy"]["se"] for c in cs)

    out += ["",
            f"* $\\rho \\le {WIN_AT_OR_BELOW}$: {sum(c['paired']['learned-greedy']['delta'] < 0 for c in lo)}"
            f"/{len(lo)} cells ahead by sign, **{sig_ahead(lo)}/{len(lo)} ahead beyond 2 SE**",
            f"* $\\rho > {WIN_AT_OR_BELOW}$: {sum(c['paired']['learned-greedy']['delta'] < 0 for c in hi)}"
            f"/{len(hi)} ahead by sign, **{sig_ahead(hi)}/{len(hi)} ahead beyond 2 SE**", ""]
    out += [
        "**Boundary.** One cell -- $k_v=8$, four agents, budget 70, `factored` backend. The",
        "curve is monotone and saturating over the swept range; no interior optimum is claimed",
        "and no floor, since $\\rho < 0.50$ was not measured. The myopic column is identical at",
        "every rate by construction: the baseline arms are the same per-episode vectors reused",
        "across rates, which is an exact pairing and a check that the comparison did not move.",
        "**MUST NOT** say \"no high-rate cell beats the myopic rule\" without the 2 SE",
        "qualifier. Two of the six high-rate cells are numerically ahead and both are inside",
        "noise; the claim is about significance, not sign, and an earlier draft of the findings",
        "note blurred the two.",
        "**MUST NOT** quote any number from `results/power/rho/` outside `deterministic/`. The",
        "pre-fix grid was scored without a seeded torch RNG and is not reproducible.", ""]

path = TR / "CLAIMS.md"
path.write_text("\n".join(out))
print(f"wrote {path.relative_to(ROOT)}: {len(out)} lines")


def build_appendix():
    """thesis/Appendix.tex -- the excluded runs, named, with what retraining did to them.

    Section 4.1 cites this. Generated rather than typed so the list cannot drift from the
    competence floor that produced it.
    """
    rows = []
    for p in sorted((TR / "sweep").glob("k*_s*.json")):
        d = json.loads(p.read_text())
        if wr(d) >= FLOOR:
            continue
        cell = p.stem.rsplit("_s", 1)[0]
        long = TR / "federation" / f"{cell}_long_s2.json"
        retrained = json.loads(long.read_text()) if long.exists() else None
        rows.append((cell, d.get("seed"), wr(d), d["arms"]["learned"]["success"],
                     wr(retrained) if retrained else None,
                     retrained["arms"]["learned"]["success"] if retrained else None,
                     d["arms"]["greedy_uncertainty"]["success"]))

    out = [r"\appendix", "", r"\chapter{Excluded Runs} \label{app:excluded}", "",
           "Every run falling below the competence floor of \\S\\ref{sec:meth_gate}, with what",
           "the same configuration reaches when trained to $12{,}000$ episodes instead of",
           "$4{,}000$. The retrained runs appear nowhere in the sweep tables of",
           "Chapter~\\ref{Chap4}, which hold the training budget fixed across all cells.", "",
           r"\begin{table}[htbp]", r"\centering",
           r"\caption{The seven excluded runs. Per-window recovery rate and joint recovery, "
           r"at the sweep's budget and at three times it.}",
           r"\label{tab:excluded}", r"\begin{tabular}{llcccccc}", r"\toprule",
           r"Cell & Seed & \multicolumn{2}{c}{4{,}000 episodes} & "
           r"\multicolumn{2}{c}{12{,}000 episodes} & Myopic \\",
           r"\cmidrule(lr){3-4}\cmidrule(lr){5-6}",
           r" & & window & joint & window & joint & joint \\", r"\midrule"]
    for cell, seed, w4, l4, w12, l12, g in rows:
        cellname = cell.replace("_", r"\_")
        tail = (f"{w12:.3f} & {l12:.3f}" if w12 is not None else "--- & ---")
        out.append(f"\\texttt{{{cellname}}} & {seed} & {w4:.3f} & {l4:.3f} & {tail} & {g:.3f} \\\\")
    out += [r"\bottomrule", r"\end{tabular}", r"\end{table}", "",
            f"All {len(rows)} excluded runs are seed 2, and all are at $k_v=12$. Every one clears",
            "the floor when retrained, and every one finishes above the myopic rule on its own",
            "cell. The floor therefore removes runs that had not finished learning rather than",
            "cells that cannot be learned.", ""]
    path = ROOT / "thesis/Appendix.tex"
    path.write_text("\n".join(out))
    print(f"wrote {path.relative_to(ROOT)}: {len(rows)} excluded runs")


build_appendix()
