"""Emit Chapter 4's axis tables at 12,000 episodes, both checkpoint conventions.

WHY A SEPARATE FILE FROM THE CHAPTER. `build_results_skeleton.py` writes the whole chapter and
would destroy the prose in it. This writes `thesis/Tables12k.tex`, which the chapter `\\input`s,
so regenerating tables after a measurement lands can never touch a sentence.

WHY BOTH CONVENTIONS. At 12,000 episodes neither is safe alone: of 21 seeds measured both ways,
8 disagree by more than a factor of three, 5 with the selected checkpoint worse and 3 with the
final worse (`FINDINGS_CHECKPOINT_TAIL_2026_09_02.md`). Reporting one column would be choosing a
convention that fails on roughly a fifth of seeds in an unpredictable direction.

A cell whose measurement has not landed emits a PENDING row rather than a blank or a plausible
number. Two silent failures today came from code that improvised instead of refusing.
"""
from __future__ import annotations
import glob, json, os, pathlib, re
import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[1]
CELL = re.compile(r"k(\d+)s(\d+)n(\d+)b(\d+)")
PRE = {"k12s50n05b150": "results/longcheck/shd_n05_12k.json",
       "k12s75n04b150": "results/longcheck/shd_s75_12k.json",
       "k12s50n08b150": "results/longcheck/shd_n08_12k.json",
       "k12s50n10b150": "results/longcheck/shd_n10_12k.json"}
# k=20 and k=30 trained at 12,000 in the original sweep and were measured there.
LEGACY = {"k20s50n04b150": ("results/ckpt/k20_best.json", "results/ckpt/k20_final.json"),
          "k30s50n04b150": ("results/ckpt/k30_best.json", "results/ckpt/k30_final.json")}

AXES = [("Window size", "k", r"$k_v$", lambda c: c["s"] == 50 and c["n"] == 4 and c["b"] == 150),
        ("Federation size", "n", r"$K$", lambda c: c["k"] == 12 and c["s"] == 50 and c["b"] == 150),
        ("Contended fraction", "s", r"$\sigma$", lambda c: c["k"] == 12 and c["n"] == 4 and c["b"] == 150),
        ("Budget multiplier", "b", r"$\beta$", lambda c: c["k"] == 12 and c["s"] == 50 and c["n"] == 4)]


def paths(cell):
    if cell in LEGACY:
        return (ROOT / LEGACY[cell][0], ROOT / LEGACY[cell][1])
    best = ROOT / PRE.get(cell, f"results/sweep12k/shd/{cell}.json")
    return (best, ROOT / f"results/sweep12k/shd_final/{cell}.json")


def stats(path, arm="learned"):
    if not path.exists():
        return None
    d = json.loads(path.read_text())
    v = [e["means"][arm]["hard"] for e in d]
    return (np.mean(v), len(v)) if v else None


def cells_on(axis_keep):
    out = {}
    for p in glob.glob(str(ROOT / "results/sweep/oracle/k*_s*.json")):
        m = CELL.match(os.path.basename(p))
        if not m:
            continue
        c = dict(k=int(m[1]), s=int(m[2]), n=int(m[3]), b=int(m[4]))
        if axis_keep(c):
            out[m.group(0)] = c
    return out


def main() -> int:
    parts = ["% Generated by scripts/build_tables12k.py. Do not edit by hand.",
             "% Chapter 4 inputs this file; regenerating it cannot touch prose.", ""]
    pending = []
    for title, key, sym, keep in AXES:
        found = cells_on(keep)
        rows = []
        for cell, c in sorted(found.items(), key=lambda kv: kv[1][key]):
            x = c[key] / 100 if key in ("s", "b") else c[key]
            bp, fp = paths(cell)
            b, f = stats(bp), stats(fp)
            g = stats(bp, "greedy") if bp.exists() else None
            if b is None or f is None or g is None:
                pending.append(cell)
                rows.append(f"{x:g} & \\multicolumn{{4}}{{c}}{{\\emph{{pending}}}} \\\\")
                continue
            rows.append(f"{x:g} & {b[0]:.5f} & {f[0]:.5f} & {g[0]:.5f} & "
                        f"{b[1]}/{f[1]} \\\\")
        parts.append("\n".join([
            r"\begin{table}[htbp]", r"\centering",
            f"\\caption{{{title} axis at $12{{,}}000$ episodes. Structural distance of the "
            r"pooled global graph on committed marks, 200 paired episodes per seed, at both "
            r"checkpoint conventions.}",
            f"\\label{{tab:12k_{key}}}", r"\begin{tabular}{rcccc}", r"\toprule",
            f"{sym} & Learned (selected) & Learned (final) & Myopic & Seeds \\\\",
            r"\midrule", *rows, r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]))

    out = ROOT / "thesis/Tables12k.tex"
    out.write_text("\n".join(parts))
    print(f"wrote {out.relative_to(ROOT)}: 4 axis tables")
    if pending:
        print(f"PENDING measurement, {len(set(pending))} cells: {sorted(set(pending))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
