"""Mark every superseded source directory, and verify the curated set never reads one.

WHY THIS EXISTS. `results/` holds about 1,100 JSON files across sixty directories, accumulated
over three weeks. Several directories were superseded during the 2--3 September work -- by the
seeded-evaluation fix, by the move to a 12,000-episode budget, or by a re-measurement that
replaced a recorded field with a paired one -- and NOTHING IN THE FILES SAYS SO. Six wrong
numbers reached a draft that way in one night, each by reading a plausible file from a
plausible directory.

Two jobs:

  1. Drop a `SUPERSEDED.md` into each superseded directory naming what replaces it and why.
     A directory that is only PARTLY superseded says which part still stands, because a blanket
     marker on `results/sweep/oracle/` would be wrong -- k=20 and k=30 exist nowhere else.

  2. Check that `scripts/collect_thesis_results.py`'s registry never points inside one. That is
     the guarantee that matters: `thesis_results/` is what the thesis quotes, and it must not be
     possible for a superseded path to reach it silently.

    python scripts/mark_provenance.py            # write markers, then verify
    python scripts/mark_provenance.py --check    # verify only, non-zero exit on a violation
"""
from __future__ import annotations
import argparse, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]

# (path, what replaces it, why, what -- if anything -- in it is STILL authoritative)
SUPERSEDED = [
    ("results/ckpt",
     "results/rerows/",
     "measured before the evaluation torch RNG was seeded (2 Sep 21:15:49), so the learned arm "
     "does not reproduce. The myopic arm in both sets is identical to five decimals, which is "
     "how the defect was isolated to the action draw.",
     None),
    ("results/power/rho/evalsweep",
     "results/power/rho/evalsweep_det/",
     "written 2 Sep 21:14, ninety seconds BEFORE the seeding fix. The timestamp is close enough "
     "to the fix to look current, which is exactly why this marker exists.",
     None),
    ("results/power/rho/argmax",
     "results/power/rho/argmax_det/",
     "superseded by COVERAGE, not by reproducibility. An earlier version of this marker said "
     "these cells were scored before the RNG was seeded and do not reproduce; that was wrong. "
     "Argmax takes the maximum logit and never draws from the torch generator, and the rebuilt "
     "cells match these digit for digit (agent B, 3 Sep 02:05). The replacement directory is "
     "authoritative because it holds all seven rates emitted by one script on one day, where "
     "this one holds two.",
     None),
    ("results/vs_generator",
     "results/generator12k/",
     "belief_backend is `version_space`, a representation the thesis no longer uses, and the "
     "metric set has no window_rate or per-pair SHD. Nothing in it can sit beside a current "
     "number.",
     None),
    ("results/sweep/oracle",
     "results/sweep12k/",
     "the 4,000-episode design. Fourteen of eighteen cells change winner at 12,000 episodes, so "
     "these runs support statements ABOUT the budget and not statements about the axes.",
     "k20s50n04b150 and k30s50n04b150 trained at 12,000 episodes and exist nowhere else. Those "
     "six runs are authoritative."),
    ("results/central",
     "results/central12k/",
     "the k=12 federation ladder at 4,000 episodes. Its one significant seed was an unconverged "
     "centralised run measuring 0.00263; at 12,000 episodes the same seed measures 0.00000.",
     "v2_k20_* trained at 12,000 episodes and are authoritative."),
]

# Directories whose JSON is authoritative but whose `global_hard_shd` field must never be read
# as the reported metric. Six wrong numbers came from that field; it scores the last update.
FIELD_WARN = [
    ("results/credit", "results/credit/shd/",
     "reading `global_hard_shd` here produced a turn-aware-credit mechanism that does not "
     "exist: pooled 15.1x against federated 13.2x once measured, not 1.0x against 18x."),
    ("results/sweep12k", "results/sweep12k/shd/, shd_final/, shd_u0500/",
     "the run files' own `global_hard_shd` is not what the thesis reports."),
]

BANNER = "# SUPERSEDED — do not quote numbers from this directory\n"


def write_markers() -> int:
    n = 0
    for rel, replacement, why, still in SUPERSEDED:
        d = ROOT / rel
        if not d.is_dir():
            continue
        body = [BANNER, "",
                f"**Replaced by `{replacement}`.**", "", why, ""]
        if still:
            body += ["## Still authoritative in this directory", "", still, ""]
        body += ["---", "",
                 "Generated by `scripts/mark_provenance.py`. `thesis_results/` is the curated "
                 "set the thesis quotes; run `scripts/collect_thesis_results.py --check` to "
                 "confirm it has not drifted, and `scripts/mark_provenance.py --check` to "
                 "confirm it does not read anything marked here.", ""]
        (d / "SUPERSEDED.md").write_text("\n".join(body))
        n += 1
    for rel, replacement, why in FIELD_WARN:
        d = ROOT / rel
        if not d.is_dir():
            continue
        (d / "READ_THE_MEASUREMENT.md").write_text(
            "# Authoritative runs, but do not read `global_hard_shd`\n\n"
            f"Structural distance for these runs is measured into `{replacement}` by "
            "`scripts/global_shd_paired.py`. The `global_hard_shd` field each run records is "
            "its own evaluation of its LAST UPDATE, not the checkpoint the thesis reports, and "
            f"the two differ by up to a factor of 300.\n\n{why}\n\n"
            "Generated by `scripts/mark_provenance.py`.\n")
        n += 1
    return n


# Reads of a superseded directory that are DELIBERATE, each with the reason. A path may only
# sit here because the thesis needs that exact superseded thing -- not because moving it is
# inconvenient. Anything not listed and not covered by a directory's own carve-out fails.
ALLOWED = {
    "results/sweep/oracle/k*s*n*b*_s?.json":
        "the 4,000-episode sweep is what Chapter 4 compares AGAINST at 12,000. It is quoted as "
        "the shorter budget and never as the result, and the collector's folder note says so.",
    "results/central/v2_k20_?_s?.json":
        "k=20 ladder runs trained at 12,000 episodes; the carve-out this directory declares.",
    "results/sweep/oracle/k*_s?.json":
        "the submission ships the 4,000-episode sweep as its own group, `sweep4k`, whose "
        "description says it is reported beside the re-run and never mixed into a table with "
        "it. Shipping it is the point: a reader checking the training-budget finding needs "
        "both budgets.",
}


def check() -> int:
    """Fail if the curated registry reads a superseded directory without a stated reason."""
    # BOTH registries. collect_thesis_results.py curates what the thesis quotes;
    # build_submission.py assembles what ships with the checkpoints. A superseded path in
    # either one reaches a reader, and they are maintained separately.
    src = "\n".join((ROOT / f).read_text() for f in
                    ("scripts/collect_thesis_results.py", "scripts/build_submission.py"))
    # Data patterns only. A registry entry also carries a prose "how to regenerate" string,
    # which mentions paths and is not a read.
    patterns = [p for p in re.findall(r'"(results/[^"]+)"', src)
                if any(ch in p for ch in "*?") and p.endswith((".json", ".sh"))
                and " " not in p]
    bad = []
    for pat in patterns:
        for rel, replacement, _why, _still in SUPERSEDED:
            if not pat.startswith(rel + "/"):
                continue
            if pat in ALLOWED:
                continue
            bad.append((pat, rel, replacement))
    for pat, rel, replacement in bad:
        print(f"  VIOLATION  registry reads {pat}\n"
              f"             {rel} is superseded by {replacement}")
    ok = len(patterns) - len(bad)
    print(f"{len(patterns)} registry data patterns checked, {ok} clean, {len(bad)} violations")
    if not bad:
        for pat, why in ALLOWED.items():
            if pat in patterns:
                print(f"  allowed    {pat}\n             {why}")
    return 1 if bad else 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    if not args.check:
        print(f"wrote {write_markers()} provenance markers")
    return check()


if __name__ == "__main__":
    sys.exit(main())
