"""Which identification criterion survives growing `d`? Policy-free.

GATE 1 failed at `d=6` because the true DAG held under 0.7 of the posterior even when it was
the clear winner (see `scripts/sa_threshold_diagnostic.py` and the log entry of 2026-08-20).
The fix is a criterion change, and the point of this script is to make that choice from
numbers rather than from argument -- so it computes EVERY candidate on the same episodes.

  dag_mass   posterior mass on the exact true DAG. The current criterion. Correct about the
             task -- pinning down the DAG really does require intervening -- but it thins out
             as `d` grows because the mass spreads over super-exponentially many graphs.
  mec_mass   mass on the true DAG's whole Markov equivalence class. Expected to be
             SATISFIABLE WITHOUT ACTING, because observational data identifies the MEC and
             nothing more. If that is what the numbers show, this criterion is disqualified
             for the single-agent task -- it would make interventions pointless -- and the
             measurement says so explicitly rather than leaving it as an assumption.

Reported at thresholds 0.5 / 0.7 / 0.9, split by whether the true graph's MEC is a singleton.
That split is the whole game: a singleton MEC is identifiable from observation alone, so it
is the only place where "observational-only identification" should ever succeed under a
criterion that is honest about the task.

The MEC is generated by COVERED-EDGE REVERSAL rather than by enumeration. Chickering (1995)
shows reversing a covered edge yields a Markov-equivalent DAG and that such reversals connect
the whole class, so a breadth-first closure from the true graph visits exactly the class --
at `d=6`, where the 3.78M-DAG list cannot be built, and at `d=3` where it can, which is what
makes the cross-check below possible.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import time
from typing import List

import numpy as np

from crosscheck.dp import DPPosterior
from ma.graphs import build_graph_space, is_singleton_mec, mec_signature
from crosscheck.score import get_score
from ma.scm import sample_multi, sample_scm_params

THRESHOLDS = (0.5, 0.7, 0.9)


def sample_dag(d: int, p: float, rng: np.random.Generator) -> np.ndarray:
    """Erdos-Renyi over a random topological order -- the same prior the DP assumes."""
    order = rng.permutation(d)
    adjacency = np.zeros((d, d), dtype=bool)
    for i in range(d):
        for j in range(i + 1, d):
            if rng.random() < p:
                adjacency[order[i], order[j]] = True
    return adjacency


def _covered_edges(adjacency: np.ndarray):
    """Edges `u -> v` with `Pa(v) \\ {u} == Pa(u)`. Reversing one keeps the DAG equivalent."""
    d = adjacency.shape[0]
    for u in range(d):
        for v in range(d):
            if not adjacency[u, v]:
                continue
            pa_v = adjacency[:, v].copy()
            pa_v[u] = False
            if np.array_equal(pa_v, adjacency[:, u]):
                yield u, v


def equivalence_class(adjacency: np.ndarray, limit: int = 200_000) -> List[np.ndarray]:
    """Every DAG Markov equivalent to `adjacency`, by covered-edge-reversal closure."""
    start = np.asarray(adjacency) > 0.5
    seen = {start.tobytes()}
    frontier = [start]
    members = [start]
    while frontier:
        current = frontier.pop()
        for u, v in _covered_edges(current):
            nxt = current.copy()
            nxt[u, v] = False
            nxt[v, u] = True
            key = nxt.tobytes()
            if key in seen:
                continue
            seen.add(key)
            members.append(nxt)
            frontier.append(nxt)
            if len(members) > limit:                        # pragma: no cover -- guard
                raise RuntimeError("equivalence class larger than the limit")
    return members


def run_d(d: int, episodes: int, n_obs: int, prior_p: float, seed: int,
          verify: bool) -> dict:
    rng = np.random.default_rng(seed)
    score = get_score("bge", d)
    dp = DPPosterior.for_prior(d, score, kind="erdos_renyi", p=prior_p)

    space = build_graph_space(d) if verify else None
    max_class_error = 0.0

    rows = []
    for _ in range(episodes):
        adjacency = sample_dag(d, prior_p, rng)
        params = sample_scm_params(adjacency, rng)
        samples, _ = sample_multi(params, n_obs, rng)
        intervened = np.zeros_like(samples, dtype=bool)

        log_w = dp.log_weights(samples, intervened)
        log_z = dp.log_partition(log_w)
        dag_mass = float(np.exp(dp.log_prob_dag(log_w, adjacency, log_z)))

        members = equivalence_class(adjacency)
        mec_mass = float(sum(np.exp(dp.log_prob_dag(log_w, m, log_z)) for m in members))

        if space is not None:
            # The covered-edge closure must reproduce the enumerated class exactly, or the
            # d=6 column below means nothing.
            signature = mec_signature(adjacency)
            enumerated = sum(1 for g in space.dags if mec_signature(g) == signature)
            max_class_error = max(max_class_error, abs(enumerated - len(members)))

        rows.append({"dag_mass": dag_mass, "mec_mass": mec_mass,
                     "class_size": len(members),
                     "singleton": bool(is_singleton_mec(adjacency))})

    def rate(key: str, threshold: float, subset=None) -> float:
        picked = [r for r in rows if subset is None or r["singleton"] == subset]
        if not picked:
            return float("nan")
        return float(np.mean([r[key] >= threshold for r in picked]))

    singleton_fraction = float(np.mean([r["singleton"] for r in rows]))
    out = {
        "d": d, "episodes": episodes, "n_obs": n_obs, "prior_p": prior_p,
        "singleton_fraction_sampled": singleton_fraction,
        "mean_class_size": float(np.mean([r["class_size"] for r in rows])),
        "dag_mass_median": float(np.median([r["dag_mass"] for r in rows])),
        "mec_mass_median": float(np.median([r["mec_mass"] for r in rows])),
        "rates": {
            key: {str(t): {"all": rate(key, t), "singleton": rate(key, t, True),
                           "non_singleton": rate(key, t, False)}
                  for t in THRESHOLDS}
            for key in ("dag_mass", "mec_mass")},
        "rows": rows,
    }
    if space is not None:
        out["max_class_size_error_vs_enumeration"] = max_class_error
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dims", default="3,4,5,6")
    ap.add_argument("--episodes", type=int, default=200)
    ap.add_argument("--n_obs", type=int, default=1000)
    ap.add_argument("--prior_p", type=float, default=0.5)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--verify_upto", type=int, default=4)
    ap.add_argument("--out", default="results/criterion_sweep.json")
    args = ap.parse_args(argv)

    report = {"args": vars(args), "by_d": {}}
    for d in [int(x) for x in args.dims.split(",")]:
        started = time.time()
        block = run_d(d, args.episodes, args.n_obs, args.prior_p, args.seed,
                      verify=(d <= args.verify_upto))
        block["seconds"] = time.time() - started
        report["by_d"][str(d)] = block
        r = block["rates"]
        print(f"d={d}  singleton {block['singleton_fraction_sampled']:.3f}  "
              f"mean|MEC| {block['mean_class_size']:.1f}", flush=True)
        for key in ("dag_mass", "mec_mass"):
            cells = "  ".join(
                f"t={t}: all {r[key][str(t)]['all']:.3f} / sing {r[key][str(t)]['singleton']:.3f}"
                for t in THRESHOLDS)
            print(f"    {key:9s} {cells}", flush=True)
        if "max_class_size_error_vs_enumeration" in block:
            print(f"    class-size check vs enumeration: max error "
                  f"{block['max_class_size_error_vs_enumeration']:.0f}", flush=True)
        print(f"    [{block['seconds']:.0f}s]", flush=True)

    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=1))
    print(f"wrote {out}")
    return report


if __name__ == "__main__":
    main()
